import { StyleSheet } from "react-native";

export default StyleSheet.create({
  body: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 170,
  },
  headBlock: { marginBottom: 8 },
  h1: { fontSize: 18, fontWeight: "950", color: "#111827" },
  h2: { marginTop: 2, fontSize: 12, fontWeight: "700", color: "#6B7280" },
  card: {
    marginTop: 10,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E6E6E6",
    borderRadius: 16,
    padding: 12,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  cardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  cardTitle: { fontSize: 16, fontWeight: "950", color: "#111827" },
  cardSub: { marginTop: 2, fontSize: 12, fontWeight: "700", color: "#6B7280" },
  goldBtn: {
    height: 34,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: "#D7B24A",
    alignItems: "center",
    justifyContent: "center",
  },
  goldBtnTxt: { fontSize: 12, fontWeight: "950", color: "#111827" },
  table: {
    marginTop: 10,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  tHead: {
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  th: { fontSize: 11, fontWeight: "950", color: "#111827" },
  thClient: { width: "34%" },
  thRate: { width: "26%" },
  thComment: { width: "40%" },
  tRow: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "flex-start",
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  tRowFirst: { borderTopWidth: 0 },
  td: { fontSize: 11, lineHeight: 16, fontWeight: "700", color: "#111827" },
  tdClient: { width: "34%" },
  tdRate: { width: "26%" },
  tdComment: { width: "40%", color: "#374151" },
  emptyBox: {
    marginTop: 16,
    height: 108,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTxt: { fontSize: 12, fontWeight: "800", color: "#6B7280" },
});
