import { Platform, StyleSheet } from "react-native";

export default StyleSheet.create({
  root: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "flex-end",
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(17,24,39,0.18)",
  },
  card: {
    marginTop: 78,
    marginRight: 12,
    width: 340,
    maxWidth: "92%",
    maxHeight: "72%",
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOpacity: Platform.OS === "web" ? 0.18 : 0.22,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
    overflow: "hidden",
  },
  head: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  title: {
    fontSize: 18,
    fontWeight: "900",
    color: "#111827",
  },
  sub: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: "700",
    color: "#6B7280",
  },
  actionBtn: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F8FAFC",
    alignItems: "center",
    justifyContent: "center",
  },
  actionTxt: {
    fontSize: 12,
    fontWeight: "900",
    color: "#111827",
  },
  list: {
    maxHeight: 420,
  },
  listContent: {
    padding: 16,
    gap: 12,
  },
  item: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFFFFF",
    padding: 14,
    gap: 6,
  },
  itemUnread: {
    backgroundColor: "#FFF9E8",
    borderColor: "#E7C55B",
  },
  itemTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  itemTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: "900",
    color: "#111827",
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#D7B24A",
  },
  itemBody: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    color: "#4B5563",
  },
  itemMeta: {
    fontSize: 11,
    fontWeight: "700",
    color: "#9CA3AF",
  },
  empty: {
    paddingVertical: 22,
    textAlign: "center",
    fontSize: 13,
    fontWeight: "700",
    color: "#6B7280",
  },
  foot: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
    alignItems: "flex-end",
  },
  closeBtn: {
    minWidth: 110,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#111827",
    alignItems: "center",
    justifyContent: "center",
  },
  closeTxt: {
    fontSize: 13,
    fontWeight: "900",
    color: "#FFFFFF",
  },
});
