import { StyleSheet } from "react-native";

export default StyleSheet.create({
  root: {
    flex: 1,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(15, 23, 42, 0.28)",
  },
  center: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 18,
  },
  card: {
    width: "100%",
    maxWidth: 520,
    maxHeight: "92%",
    alignSelf: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  headerCopy: {
    flex: 1,
  },
  title: {
    fontSize: 17,
    fontWeight: "950",
    color: "#111827",
  },
  subtitle: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 18,
    color: "#6B7280",
  },
  closeIconBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F3F4F6",
  },
  closeIconTxt: {
    fontSize: 18,
    fontWeight: "900",
    color: "#111827",
    lineHeight: 20,
  },
  scrollBody: {
    padding: 14,
    gap: 12,
  },
  topMeta: {
    flexDirection: "row",
    gap: 10,
  },
  metaCard: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F8FAFC",
    padding: 12,
  },
  metaLabel: {
    fontSize: 11,
    fontWeight: "900",
    color: "#6B7280",
    textTransform: "uppercase",
  },
  metaValue: {
    marginTop: 5,
    fontSize: 13,
    fontWeight: "900",
    color: "#111827",
  },
  section: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  sectionTitle: {
    marginBottom: 10,
    fontSize: 12,
    fontWeight: "950",
    color: "#111827",
    textTransform: "uppercase",
  },
  sectionNote: {
    marginTop: 10,
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 16,
    color: "#6B7280",
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 5,
  },
  infoLabel: {
    flex: 1,
    fontSize: 12,
    fontWeight: "800",
    color: "#6B7280",
  },
  infoValue: {
    flex: 1,
    fontSize: 12,
    fontWeight: "800",
    color: "#111827",
    textAlign: "right",
  },
  badge: {
    marginLeft: "auto",
    minHeight: 24,
    paddingHorizontal: 10,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#FFFFFF",
  },
  proofImage: {
    width: "100%",
    height: 180,
    borderRadius: 14,
    backgroundColor: "#F3F4F6",
  },
  breakdownCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  breakdownRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  breakdownRowTotal: {
    borderBottomWidth: 0,
    paddingTop: 10,
  },
  breakdownLabel: {
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
    color: "#374151",
  },
  breakdownLabelTotal: {
    fontWeight: "950",
    color: "#111827",
  },
  breakdownValue: {
    fontSize: 12,
    fontWeight: "900",
    color: "#111827",
    textAlign: "right",
  },
  breakdownValueTotal: {
    fontSize: 14,
  },
  actions: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    paddingTop: 4,
  },
  closeBtn: {
    minHeight: 44,
    borderRadius: 14,
    backgroundColor: "#D7B24A",
    borderWidth: 1,
    borderColor: "#B38B1F",
    alignItems: "center",
    justifyContent: "center",
  },
  closeTxt: {
    fontSize: 13,
    fontWeight: "900",
    color: "#111827",
  },
});
