import { StyleSheet } from "react-native";

export default StyleSheet.create({
  body: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 30,
  },
  topRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  h1: { fontSize: 18, fontWeight: "950", color: "#111827" },
  h2: { marginTop: 2, fontSize: 12, fontWeight: "700", color: "#6B7280" },
  exportBtn: {
    backgroundColor: "#111827",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  exportTxt: { color: "#FFF", fontWeight: "900", fontSize: 12 },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  searchBox: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 16,
    paddingHorizontal: 12,
    height: 46,
  },
  searchIcon: { width: 18, height: 18, opacity: 0.65 },
  searchInput: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: "#111827",
  },
  filterBtn: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  filterIcon: { width: 20, height: 20, opacity: 0.75 },
  tableCard: {
    marginTop: 10,
    backgroundColor: "#FFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  tableHead: {
    flexDirection: "row",
    backgroundColor: "#D1D5DB",
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  th: { fontSize: 11, fontWeight: "950", color: "#111827" },
  td: { fontSize: 11, lineHeight: 16, fontWeight: "800", color: "#111827" },
  tr: {
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    alignItems: "center",
  },
  trLast: { borderBottomWidth: 0 },
  trLow: { backgroundColor: "#FEE2E2" },
  colId: { flex: 0.9 },
  colName: { flex: 1.3 },
  colRemain: { flex: 1.2 },
  colRemarks: { flex: 1.2 },
  colAction: { flex: 0.9 },
  actionCell: { alignItems: "flex-end" },
  restockBtn: {
    marginTop: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D7B24A",
    backgroundColor: "#F6E7B6",
  },
  restockTxt: { fontSize: 10, fontWeight: "900", color: "#111827" },
  viewBtn: {
    minHeight: 28,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    backgroundColor: "#FFFFFF",
  },
  viewTxt: { fontSize: 10, fontWeight: "900", color: "#111827" },
  pager: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  pageBtn: {
    width: 44,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
  },
  pageTxt: { fontSize: 16, fontWeight: "900", color: "#111827" },
  pageNum: {
    width: 44,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
  },
  pageNumTxt: { fontSize: 13, fontWeight: "950", color: "#111827" },
  emptyRow: { paddingVertical: 14, paddingHorizontal: 10 },
  emptyTxt: { fontSize: 11, fontWeight: "800", color: "#111827" },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    padding: 16,
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  modalCard: {
    backgroundColor: "#FFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 14,
  },
  modalTitle: { fontSize: 16, fontWeight: "950", color: "#111827" },
  modalSub: { marginTop: 4, fontSize: 12, fontWeight: "700", color: "#6B7280" },
  modalLabel: {
    marginTop: 12,
    marginBottom: 6,
    fontSize: 12,
    fontWeight: "900",
    color: "#111827",
  },
  modalInputWrap: {
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFF",
    paddingHorizontal: 12,
    justifyContent: "center",
  },
  modalInput: {
    fontSize: 13,
    fontWeight: "700",
    color: "#111827",
  },
  modalInputDisabledWrap: {
    backgroundColor: "#F3F4F6",
  },
  modalInputDisabledTxt: {
    fontSize: 13,
    fontWeight: "700",
    color: "#6B7280",
  },
  modalTextAreaWrap: {
    minHeight: 82,
    paddingTop: 10,
    paddingBottom: 10,
  },
  modalTextArea: {
    minHeight: 60,
    textAlignVertical: "top",
  },
  modalActions: {
    marginTop: 14,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  modalBtn: {
    minHeight: 42,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#D7B24A",
  },
  modalBtnTxt: {
    fontSize: 13,
    fontWeight: "900",
    color: "#111827",
  },
  modalBtnGhost: {
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  modalBtnGhostTxt: {
    fontSize: 13,
    fontWeight: "900",
    color: "#111827",
  },
});
