import { StyleSheet } from "react-native";

export default StyleSheet.create({
  body: { paddingHorizontal: 12, paddingTop: 10, paddingBottom: 30 },
  topRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  h1: { fontSize: 18, fontWeight: "950", color: "#111827" },
  h2: { marginTop: 2, fontSize: 12, fontWeight: "700", color: "#6B7280" },
  exportBtn: {
    backgroundColor: "#111827",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  exportTxt: { color: "#FFF", fontWeight: "900", fontSize: 12 },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  searchBox: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 16,
    paddingHorizontal: 12,
    height: 46,
  },
  searchIcon: { width: 18, height: 18, opacity: 0.65 },
  searchInput: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: "#111827",
  },
  filterBtn: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  filterIcon: { width: 20, height: 20, opacity: 0.75 },
  toolbarRow: {
    marginBottom: 8,
  },
  modeToggle: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    padding: 4,
    gap: 4,
  },
  modeBtn: {
    flex: 1,
    minHeight: 38,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  modeBtnActive: {
    backgroundColor: "#FEF3C7",
  },
  modeTxt: { color: "#6B7280", fontWeight: "900", fontSize: 12 },
  modeTxtActive: { color: "#111827" },
  resultsTxt: {
    marginTop: 2,
    marginBottom: 10,
    fontSize: 12,
    fontWeight: "800",
    color: "#6B7280",
  },
  listCard: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  logCard: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  logCardLast: { borderBottomWidth: 0 },
  logTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 12,
  },
  logIdBadge: {
    flexShrink: 1,
    minHeight: 30,
    borderRadius: 999,
    backgroundColor: "#FEF3C7",
    borderWidth: 1,
    borderColor: "#D4A72C",
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  logIdTxt: {
    fontSize: 10,
    fontWeight: "950",
    color: "#111827",
  },
  logMetaGrid: {
    gap: 10,
  },
  logField: {
    gap: 4,
  },
  logFieldLabel: {
    fontSize: 10,
    fontWeight: "900",
    color: "#6B7280",
  },
  logFieldValue: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "800",
    color: "#111827",
  },
  emptyRow: { paddingVertical: 14, paddingHorizontal: 10 },
  emptyTxt: { fontSize: 11, fontWeight: "800", color: "#111827" },
  rowActionBtn: {
    minWidth: 92,
    minHeight: 34,
    borderRadius: 999,
    backgroundColor: "#111827",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  rowActionBtnGhost: {
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#D1D5DB",
  },
  rowActionBtnDisabled: {
    backgroundColor: "#D1D5DB",
    borderColor: "#D1D5DB",
  },
  rowActionTxt: {
    fontSize: 11,
    fontWeight: "900",
    color: "#FFF",
  },
  rowActionTxtGhost: {
    color: "#111827",
  },
  rowActionTxtDisabled: {
    color: "#6B7280",
  },
  pager: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  pageBtn: {
    width: 44,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
  },
  pageTxt: { fontSize: 16, fontWeight: "900", color: "#111827" },
  pageNum: {
    width: 44,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
  },
  pageNumTxt: { fontSize: 13, fontWeight: "950", color: "#111827" },
});
