import { StyleSheet } from "react-native";

export default StyleSheet.create({
  body: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 30,
  },
  topRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  h1: { fontSize: 22, fontWeight: "950", color: "#111827" },
  h2: { marginTop: 2, fontSize: 13, fontWeight: "700", color: "#6B7280" },
  exportBtn: {
    backgroundColor: "#111827",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  exportTxt: { color: "#FFF", fontWeight: "900", fontSize: 12 },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 14,
  },
  searchBox: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    paddingHorizontal: 12,
    height: 46,
  },
  searchIcon: {
    width: 17,
    height: 17,
    opacity: 0.65,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: "#111827",
  },
  searchBtn: {
    height: 46,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: "#111827",
    alignItems: "center",
    justifyContent: "center",
  },
  searchBtnTxt: {
    color: "#FFF",
    fontSize: 12,
    fontWeight: "900",
  },
  filterBtn: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  filterBtnActive: {
    backgroundColor: "#F3F4F6",
    borderColor: "#111827",
  },
  filterIcon: {
    width: 20,
    height: 20,
    opacity: 0.75,
  },
  filterCard: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 12,
    marginTop: 10,
  },
  filterHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  filterTitle: {
    fontSize: 13,
    fontWeight: "900",
    color: "#111827",
  },
  clearFilterTxt: {
    fontSize: 12,
    fontWeight: "800",
    color: "#B91C1C",
  },
  filterLabel: {
    fontSize: 12,
    fontWeight: "900",
    color: "#374151",
    marginBottom: 8,
  },
  filterChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  filterChip: {
    paddingHorizontal: 12,
    minHeight: 34,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
  },
  filterChipActive: {
    backgroundColor: "#111827",
    borderColor: "#111827",
  },
  filterChipTxt: {
    fontSize: 11,
    fontWeight: "800",
    color: "#374151",
  },
  filterChipTxtActive: {
    color: "#FFF",
  },
  resultsTxt: {
    marginTop: 10,
    fontSize: 12,
    fontWeight: "700",
    color: "#6B7280",
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 10,
  },
  statCard: {
    width: "48.5%",
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 16,
    padding: 14,
  },
  statValue: { fontSize: 18, fontWeight: "950", color: "#111827" },
  statLabel: { marginTop: 4, fontSize: 12, fontWeight: "700", color: "#6B7280" },
  section: { marginTop: 16 },
  sectionTitle: { fontSize: 16, fontWeight: "950", color: "#111827" },
  stack: { marginTop: 10, gap: 10 },
  rowCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 16,
    padding: 14,
  },
  rowTitle: { fontSize: 13, fontWeight: "900", color: "#111827" },
  rowSub: { marginTop: 2, fontSize: 12, fontWeight: "700", color: "#6B7280" },
  rowValue: { fontSize: 13, fontWeight: "950", color: "#111827" },
  emptyCard: {
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 16,
    padding: 14,
  },
  emptyTxt: { fontSize: 12, fontWeight: "700", color: "#6B7280" },
});
