import { StyleSheet } from "react-native";

export default StyleSheet.create({
  body: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 30,
  },
  topRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  h1: { fontSize: 18, fontWeight: "950", color: "#111827" },
  h2: { marginTop: 2, fontSize: 12, fontWeight: "700", color: "#6B7280" },
  exportBtn: {
    backgroundColor: "#111827",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  exportTxt: { color: "#FFF", fontWeight: "900", fontSize: 12 },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  searchBox: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 16,
    paddingHorizontal: 12,
    height: 46,
  },
  searchIcon: { width: 18, height: 18, opacity: 0.65 },
  searchInput: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: "#111827",
  },
  filterBtn: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  filterIcon: { width: 20, height: 20, opacity: 0.75 },
  tableCard: {
    marginTop: 10,
    backgroundColor: "#FFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  tableHead: {
    flexDirection: "row",
    backgroundColor: "#D1D5DB",
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  th: { fontSize: 11, fontWeight: "950", color: "#111827" },
  td: { fontSize: 11, lineHeight: 16, fontWeight: "800", color: "#111827" },
  tr: {
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    alignItems: "center",
  },
  trLast: { borderBottomWidth: 0 },
  colId: { flex: 0.9 },
  colCustomer: { flex: 1.3 },
  colAction: { flex: 1 },
  colStatus: { flex: 1 },
  statusCell: {
    justifyContent: "center",
    alignItems: "flex-start",
  },
  actionCell: { alignItems: "flex-end" },
  statusPill: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
  },
  statusTxt: {
    fontSize: 10,
    fontWeight: "950",
    color: "#111827",
  },
  stInProgress: { backgroundColor: "#DBEAFE" },
  stCompleted: { backgroundColor: "#DCFCE7" },
  stArrived: { backgroundColor: "#FEF3C7" },
  stBooked: { backgroundColor: "#FED7AA" },
  viewBtn: {
    minHeight: 28,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    backgroundColor: "#FFFFFF",
  },
  viewTxt: { fontSize: 10, fontWeight: "900", color: "#111827" },
  pager: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  pageBtn: {
    width: 44,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
  },
  pageTxt: { fontSize: 16, fontWeight: "900", color: "#111827" },
  pageNum: {
    width: 44,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
  },
  pageNumTxt: { fontSize: 13, fontWeight: "950", color: "#111827" },
});
