import { StyleSheet } from "react-native";

export default StyleSheet.create({
  body: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 30,
    gap: 12,
  },
  topBar: {
    gap: 10,
  },
  dateFilterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dateInput: {
    flex: 1,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D7DEEA",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    fontSize: 12,
    fontWeight: "800",
    color: "#111827",
  },
  topActions: {
    flexDirection: "row",
    gap: 8,
  },
  pageIntro: {
    marginTop: 2,
  },
  h1: {
    fontSize: 22,
    fontWeight: "950",
    color: "#111827",
  },
  h2: {
    marginTop: 2,
    fontSize: 13,
    fontWeight: "700",
    color: "#6B7280",
  },
  exportBtn: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: "#111827",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  exportTxt: {
    color: "#FFFFFF",
    fontWeight: "900",
    fontSize: 12,
  },
  primaryBtn: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: "#FFF3C7",
    borderWidth: 1,
    borderColor: "rgba(216, 177, 47, 0.55)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  primaryBtnTxt: {
    color: "#111827",
    fontWeight: "950",
    fontSize: 12,
  },
  ghostBtn: {
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D7DEEA",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  ghostBtnTxt: {
    color: "#374151",
    fontWeight: "900",
    fontSize: 12,
  },
  topGrid: {
    gap: 12,
  },
  leftStack: {
    gap: 12,
  },
  rightStack: {
    gap: 12,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 18,
    padding: 14,
    shadowColor: "#0F172A",
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  cardHead: {
    gap: 10,
    marginBottom: 12,
  },
  cardHeadStack: {
    gap: 12,
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "950",
    color: "#111827",
  },
  cardSub: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: "700",
    color: "#6B7280",
    lineHeight: 18,
  },
  inlineFilters: {
    gap: 10,
  },
  inlineSearchBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D7DEEA",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
  },
  searchIcon: {
    width: 16,
    height: 16,
    opacity: 0.68,
  },
  inlineSearchInput: {
    flex: 1,
    fontSize: 12,
    fontWeight: "800",
    color: "#111827",
  },
  typeChipRow: {
    gap: 8,
    paddingRight: 12,
  },
  typeChip: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  typeChipActive: {
    backgroundColor: "#111827",
    borderColor: "#111827",
  },
  typeChipTxt: {
    fontSize: 11,
    fontWeight: "800",
    color: "#374151",
  },
  typeChipTxtActive: {
    color: "#FFFFFF",
  },
  tableHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  tableHeaderTxt: {
    fontSize: 11,
    fontWeight: "950",
    color: "#475569",
    textTransform: "uppercase",
  },
  tableRowCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#EEF2F7",
  },
  dateCol: {
    width: 70,
  },
  descriptionCol: {
    flex: 1,
  },
  categoryCol: {
    width: 86,
    alignItems: "flex-start",
  },
  amountCol: {
    width: 72,
    textAlign: "right",
  },
  commissionDateCol: {
    width: 70,
  },
  commissionWorkerCol: {
    width: 88,
  },
  commissionRoleCol: {
    width: 70,
  },
  commissionServiceCol: {
    flex: 1,
    minWidth: 92,
  },
  commissionTallyCol: {
    width: 78,
    textAlign: "right",
  },
  commissionRateCol: {
    width: 42,
    textAlign: "center",
  },
  commissionEarnedCol: {
    width: 74,
    textAlign: "right",
  },
  tableDateTxt: {
    fontSize: 12,
    fontWeight: "800",
    color: "#111827",
  },
  mainTxt: {
    fontSize: 12,
    fontWeight: "900",
    color: "#111827",
  },
  subTxt: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: "700",
    color: "#6B7280",
    lineHeight: 16,
  },
  metaTxt: {
    marginTop: 4,
    fontSize: 11,
    fontWeight: "700",
    color: "#64748B",
  },
  metaTxtStrong: {
    fontSize: 12,
    fontWeight: "800",
    color: "#374151",
  },
  amountTxt: {
    fontSize: 12,
    fontWeight: "950",
    color: "#111827",
  },
  tag: {
    minHeight: 28,
    paddingHorizontal: 10,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  tagTxt: {
    fontSize: 10,
    fontWeight: "900",
    color: "#111827",
  },
  tag_violet: {
    backgroundColor: "#F3E8FF",
  },
  tag_cyan: {
    backgroundColor: "#E0F2FE",
  },
  tag_amber: {
    backgroundColor: "#FEF3C7",
  },
  tag_green: {
    backgroundColor: "#DCFCE7",
  },
  tag_pink: {
    backgroundColor: "#FCE7F3",
  },
  footerStat: {
    marginTop: 12,
    fontSize: 12,
    fontWeight: "900",
    color: "#111827",
  },
  pagerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    marginTop: 10,
  },
  pagerBtn: {
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#D7DEEA",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  pagerBtnDisabled: {
    opacity: 0.45,
  },
  pagerBtnTxt: {
    fontSize: 12,
    fontWeight: "950",
    color: "#111827",
  },
  pagerCurrent: {
    minWidth: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#D7DEEA",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  pagerCurrentTxt: {
    fontSize: 12,
    fontWeight: "950",
    color: "#111827",
  },
  compareSummary: {
    gap: 8,
  },
  compareChip: {
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  compareChipRevenue: {
    backgroundColor: "#ECFDF5",
    borderColor: "#A7F3D0",
  },
  compareChipExpense: {
    backgroundColor: "#FEF2F2",
    borderColor: "#FECACA",
  },
  compareChipCommission: {
    backgroundColor: "#EEF2FF",
    borderColor: "#C7D2FE",
  },
  compareChipLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "#475569",
  },
  compareChipValue: {
    marginTop: 4,
    fontSize: 15,
    fontWeight: "950",
    color: "#047857",
  },
  compareChipValueExpense: {
    color: "#DC2626",
  },
  compareChipValueCommission: {
    color: "#3158D8",
  },
  barRow: {
    marginTop: 10,
  },
  barLabel: {
    marginBottom: 6,
    fontSize: 12,
    fontWeight: "900",
    color: "#111827",
  },
  barTrack: {
    height: 28,
    borderRadius: 999,
    backgroundColor: "#F3F4F6",
    overflow: "hidden",
    justifyContent: "center",
  },
  barFill: {
    minWidth: 32,
    height: "100%",
    justifyContent: "center",
    paddingHorizontal: 10,
    borderRadius: 999,
  },
  barFill_revenue: {
    backgroundColor: "#059669",
  },
  barFill_expense: {
    backgroundColor: "#E32626",
  },
  barFill_commission: {
    backgroundColor: "#3158D8",
  },
  barFillZero: {
    backgroundColor: "#CBD5E1",
  },
  barValue: {
    fontSize: 11,
    fontWeight: "900",
    color: "#FFFFFF",
  },
  netProfitCard: {
    marginTop: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F8FAFC",
    padding: 12,
  },
  netProfitLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: "#475569",
  },
  netProfitValue: {
    marginTop: 4,
    fontSize: 18,
    fontWeight: "950",
    color: "#111827",
  },
  interpretationHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 12,
  },
  aiPill: {
    borderRadius: 999,
    backgroundColor: "#FFF7D6",
    borderWidth: 1,
    borderColor: "#E7CF77",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  aiPillDisabled: {
    opacity: 0.65,
  },
  aiPillTxt: {
    fontSize: 10,
    fontWeight: "900",
    color: "#7C5E10",
  },
  interpretationList: {
    gap: 8,
  },
  aiSummaryCard: {
    borderRadius: 16,
    backgroundColor: "rgba(248,211,95,0.12)",
    borderWidth: 1,
    borderColor: "rgba(248,211,95,0.35)",
    padding: 14,
  },
  aiSummaryLabel: {
    fontSize: 11,
    fontWeight: "950",
    color: "#B45309",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  aiSummaryTxt: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: "800",
    color: "#111827",
    lineHeight: 20,
  },
  aiSectionCard: {
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 12,
  },
  aiSectionCardWarning: {
    backgroundColor: "#FFF4F4",
    borderColor: "#FECACA",
  },
  aiSectionTitle: {
    fontSize: 13,
    fontWeight: "950",
    color: "#111827",
  },
  aiBulletList: {
    marginTop: 10,
    gap: 10,
  },
  aiBulletRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  aiBulletDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    marginTop: 5,
    backgroundColor: "#F8D35F",
  },
  aiBulletDotWarning: {
    backgroundColor: "#F87171",
  },
  aiBulletTxt: {
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
    color: "#111827",
    lineHeight: 19,
  },
  interpretationItem: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFFFFF",
    padding: 12,
  },
  interpretationItemMuted: {
    backgroundColor: "#FFFBEA",
    borderColor: "#F3E3A1",
  },
  interpretationTxt: {
    fontSize: 12,
    fontWeight: "700",
    color: "#374151",
    lineHeight: 18,
  },
  interpretationTxtMuted: {
    color: "#7C5E10",
  },
  commissionCard: {
    marginTop: 2,
  },
  commissionSummary: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: "900",
    color: "#3158D8",
  },
  commissionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    marginBottom: 2,
  },
  emptyCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F9FAFB",
    padding: 14,
    marginTop: 10,
  },
  emptyTxt: {
    fontSize: 12,
    fontWeight: "700",
    color: "#6B7280",
    lineHeight: 18,
  },
  modalOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(15, 23, 42, 0.34)",
  },
  modalCenter: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 18,
  },
  modalCard: {
    width: "100%",
    maxWidth: 420,
    maxHeight: "90%",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFFFFF",
    padding: 16,
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  modalCloseBtn: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  modalCloseTxt: {
    fontSize: 16,
    fontWeight: "950",
    color: "#111827",
  },
  modalHeader: {
    marginBottom: 12,
    paddingRight: 24,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "950",
    color: "#111827",
  },
  modalSub: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: "700",
    color: "#6B7280",
    lineHeight: 18,
  },
  modalGrid: {
    gap: 12,
  },
  field: {
    gap: 6,
  },
  fieldWide: {
    width: "100%",
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: "900",
    color: "#374151",
  },
  fieldInput: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D7DEEA",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    fontSize: 12,
    fontWeight: "800",
    color: "#111827",
  },
  fieldTextarea: {
    minHeight: 90,
    paddingTop: 12,
  },
  modalChipRow: {
    gap: 8,
    paddingRight: 10,
  },
  modalChip: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  modalChipActive: {
    backgroundColor: "#111827",
    borderColor: "#111827",
  },
  modalChipTxt: {
    fontSize: 11,
    fontWeight: "800",
    color: "#374151",
  },
  modalChipTxtActive: {
    color: "#FFFFFF",
  },
  modalError: {
    marginTop: 12,
    fontSize: 12,
    fontWeight: "800",
    color: "#DC2626",
    lineHeight: 18,
  },
  modalActions: {
    flexDirection: "row",
    gap: 8,
    marginTop: 14,
  },
});
