import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f3f4f6",
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 36,
    gap: 14,
  },
  heroCard: {
    backgroundColor: "#0f172a",
    borderRadius: 22,
    padding: 18,
  },
  eyebrow: {
    color: "#93c5fd",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 8,
  },
  heroTitle: {
    color: "#f8fafc",
    fontSize: 22,
    fontWeight: "800",
  },
  heroSub: {
    color: "#cbd5e1",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 8,
  },
  exportButton: {
    marginTop: 14,
    alignSelf: "flex-start",
    backgroundColor: "#f59e0b",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
  },
  exportButtonText: {
    color: "#111827",
    fontWeight: "800",
    fontSize: 12,
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 14,
  },
  statLabel: {
    color: "#6b7280",
    fontSize: 12,
    marginBottom: 8,
  },
  statValue: {
    color: "#111827",
    fontSize: 22,
    fontWeight: "800",
  },
  panel: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 14,
  },
  panelTitle: {
    color: "#111827",
    fontSize: 17,
    fontWeight: "800",
  },
  panelSub: {
    color: "#6b7280",
    fontSize: 13,
    marginTop: 4,
    marginBottom: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#f9fafb",
    color: "#111827",
    marginBottom: 10,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  searchBox: {
    flex: 1,
    minHeight: 48,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 16,
    backgroundColor: "#f9fafb",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
  },
  searchIcon: {
    width: 16,
    height: 16,
    tintColor: "#6b7280",
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    color: "#111827",
    paddingVertical: 12,
    fontSize: 13,
  },
  filterBtn: {
    width: 48,
    height: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  filterBtnActive: {
    backgroundColor: "#dbeafe",
    borderColor: "#60a5fa",
  },
  filterIcon: {
    width: 18,
    height: 18,
    tintColor: "#1f2937",
  },
  resultsText: {
    color: "#6b7280",
    fontSize: 12,
    marginTop: 10,
  },
  activeFiltersRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
  },
  chipActive: {
    backgroundColor: "#dbeafe",
    borderColor: "#60a5fa",
  },
  chipText: {
    color: "#374151",
    fontSize: 12,
    fontWeight: "700",
  },
  chipTextActive: {
    color: "#1d4ed8",
  },
  recordCard: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 18,
    padding: 14,
    marginTop: 12,
    backgroundColor: "#fcfcfd",
  },
  recordTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
  },
  recordTitle: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "800",
    flex: 1,
  },
  recordMeta: {
    color: "#6b7280",
    fontSize: 12,
    marginTop: 3,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#e5e7eb",
  },
  badgeText: {
    color: "#111827",
    fontSize: 11,
    fontWeight: "800",
  },
  detailGrid: {
    marginTop: 12,
    gap: 8,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  detailLabel: {
    color: "#6b7280",
    fontSize: 12,
    flex: 1,
  },
  detailValue: {
    color: "#111827",
    fontSize: 12,
    fontWeight: "700",
    flex: 1,
    textAlign: "right",
  },
  actionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 14,
  },
  actionButton: {
    backgroundColor: "#111827",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  actionButtonAlt: {
    backgroundColor: "#0f766e",
  },
  actionButtonWarn: {
    backgroundColor: "#b91c1c",
  },
  actionButtonDisabled: {
    backgroundColor: "#d1d5db",
  },
  actionButtonText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "800",
  },
  emptyText: {
    color: "#6b7280",
    fontSize: 13,
    textAlign: "center",
    paddingVertical: 18,
  },
  pager: {
    marginTop: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  pageBtn: {
    width: 38,
    height: 38,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  pageBtnDisabled: {
    opacity: 0.45,
  },
  pageTxt: {
    fontSize: 16,
    fontWeight: "900",
    color: "#111827",
  },
  pageNum: {
    minWidth: 42,
    height: 38,
    borderRadius: 999,
    backgroundColor: "#e5e7eb",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  pageNumTxt: {
    fontSize: 13,
    fontWeight: "950",
    color: "#111827",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.54)",
    justifyContent: "center",
    padding: 18,
  },
  modalCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    maxHeight: "88%",
    overflow: "hidden",
  },
  modalScroll: {
    padding: 18,
  },
  modalTitle: {
    color: "#111827",
    fontSize: 20,
    fontWeight: "800",
  },
  modalSub: {
    color: "#6b7280",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
    marginBottom: 14,
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 14,
  },
  secondaryButton: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 12,
    backgroundColor: "#e5e7eb",
  },
  secondaryButtonText: {
    color: "#111827",
    fontWeight: "800",
  },
  primaryButton: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 12,
    backgroundColor: "#111827",
  },
  primaryButtonText: {
    color: "#ffffff",
    fontWeight: "800",
  },
  errorText: {
    color: "#b91c1c",
    fontSize: 12,
    marginTop: 8,
  },
});
